version: '3.8'

services:
  backend:
    # Coloque aqui o seu usuário do Docker Hub
    image: laiootavares/laink-backend:1.0
    container_name: laink-backend-container
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # A URL agora usa variáveis que vamos configurar no Portainer
      - DATABASE_URL=postgresql://lainkuser:${DB_PASSWORD}@laink-postgres-db:5432/lainkdb
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3333
    networks:
      - meu-stack_default

networks:
  meu-stack_default:
    external: true